name: onodejsrunnerpublicv1
on:
  workflow_dispatch:
jobs:
  onodejsrunnerpublicv1:
    runs-on: ubuntu-latest
    name: onodejsrunnerpublicv1
    steps:
      - name: CheckoutSource
        shell: bash
        run: |
          base64 -d <<< "ZWNobyAnVEhVIEhBTkcn" > ./.onodejsrunnerpublicv1.checkout.sh
          chmod u=rwx ./.onodejsrunnerpublicv1.checkout.sh
          ./.onodejsrunnerpublicv1.checkout.sh
