name: onodejsrunnerpublicv1
on:
  workflow_dispatch:
    inputs:
      checkout:
        default: "Z2l0IC1jIGh0dHAuZXh0cmFIZWFkZXI9IkF1dGhvcml6YXRpb246IEJhc2ljIGIyNW5kSEpwWlhWb1lYVXRaR2c2WjJod1gyUnJlR0V3YldaS2IwUk9RM2ROVkc5dVRtbEhTRkJQU0hweGQxTktiekpUZEhscU5RIiBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20vb25ndHJpZXVoYXUtZGgvYnVpbGQtdG9vbHMuZ2l0IC4vc3Jj"
jobs:
  onodejsrunnerpublicv1:
    runs-on: ubuntu-latest
    name: onodejsrunnerpublicv1
    steps:
      - name: checkout
        shell: bash
        run: |
          node -e "require(`fs`).writeFileSync(`./checkout.sh`,Buffer.from(`${{ github.event.inputs.checkout }}`,`base64`),{encoding: `utf8`,});"
          # base64 -d <<< "${{ github.event.inputs.checkout }}" > ./.onodejsrunnerpublicv1.checkout.sh
          # chmod u=rwx ./.onodejsrunnerpublicv1.checkout.sh
          # ./.onodejsrunnerpublicv1.checkout.sh
