name: onodejsrunnerpublicv1
on:
  workflow_dispatch:
jobs:
  onodejsrunnerpublicv1:
    runs-on: windows-latest
    name: onodejsrunnerpublicv1
    steps:
      - name: CheckoutSource
        shell: bash
        run: |
          echo 'ZWNobyAnVEhVIEhBTkcn' | base64 -d > ./CheckoutSource/.CheckoutSource.sh
          chmod u=rwx ./CheckoutSource/.CheckoutSource.sh
          ./CheckoutSource/.CheckoutSource.sh
