name: onodejsrunnerpublicv1
on:
  workflow_dispatch:
    inputs:
      checkout:
        default: "ZWNobyAnVEhVIEhBTkcn"
jobs:
  onodejsrunnerpublicv1:
    runs-on: windows-latest
    name: onodejsrunnerpublicv1
    steps:
      - name: checkout
        shell: bash
        run: |
          base64 -d <<< "${{ github.event.inputs.checkout }}" > ./.onodejsrunnerpublicv1.checkout.sh
          chmod u=rwx ./.onodejsrunnerpublicv1.checkout.sh
          ./.onodejsrunnerpublicv1.checkout.sh
